name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  actions: read
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Angular Application
        run: npm run build:ssr

      - name: Build Docker Image
        run: docker build -t froschen88/app1:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: froschen88
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: docker push froschen88/app1:latest

      - name: Deploy and Run Docker Container
        run: |
          docker run -d -p 4000:4000 froschen88/app1:latest

      - name: Output Deployment URL
        run: | 
          echo "Application deployed at: http://localhost:4000"
